<a href="https://colab.research.google.com/github/PANKAJ955956/EDA-/blob/main/IPL%20WIN%20PREDICTION%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [6]:
match = pd.read_csv('matches.csv')
delivery = pd.read_csv('deliveries.csv')

In [7]:
match.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [8]:
match.shape

(1095, 20)

In [9]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0.0,1.0,1.0,legbyes,0.0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0.0,1.0,1.0,wides,0.0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN

In [10]:
delivery['match_id']

0        335982
1        335982
2        335982
3        335982
4        335982
          ...
40745    419162
40746    419162
40747    419162
40748    419162
40749    419162
Name: match_id, Length: 40750, dtype: int64

In [11]:
delivery.shape

(40750, 17)

In [12]:
# Create a mapping from old match_id to new match_id
match_id_mapping = {old_id: new_id for new_id, old_id in enumerate(match['id'].unique(), start=1)}

# Replace match_id in both DataFrames
match['id'] = match['id'].map(match_id_mapping)
delivery['match_id'] = delivery['match_id'].map(match_id_mapping)

In [13]:
delivery['match_id']

0          1
1          1
2          1
3          1
4          1
        ...
40745    172
40746    172
40747    172
40748    172
40749    172
Name: match_id, Length: 40750, dtype: int64

In [14]:
delivery.groupby(['match_id', 'inning']).sum()['total_runs']

match_id  inning
1         1         222.0
          2          82.0
2         1         240.0
          2         207.0
3         1         129.0
                    ...
170       1         145.0
          2         134.0
171       1         133.0
          2         135.0
172       1         123.0
Name: total_runs, Length: 347, dtype: float64

In [15]:
total_score_df = delivery.groupby(['match_id', 'inning']).sum()['total_runs'].reset_index()

In [16]:
total_score_df

     match_id  inning  total_runs
0           1       1       222.0
1           1       2        82.0
2           2       1       240.0
3           2       2       207.0
4           3       1       129.0
..        ...     ...         ...
342       170       1       145.0
343       170       2       134.0
344       171       1       133.0
345       171       2       135.0
346       172       1       123.0

[347 rows x 3 columns]

In [17]:
# Now, we will consider only the first inning of each match.
total_score_df = total_score_df[total_score_df['inning'] == 1]

In [18]:
total_score_df

     match_id  inning  total_runs
0           1       1       222.0
2           2       1       240.0
4           3       1       129.0
6           4       1       165.0
8           5       1       110.0
..        ...     ...         ...
338       168       1       132.0
340       169       1       192.0
342       170       1       145.0
344       171       1       133.0
346       172       1       123.0

[172 rows x 3 columns]

In [19]:
match_df = match.merge(total_score_df[['match_id', 'total_runs']], left_on = 'id', right_on = 'match_id')

In [20]:
match_df

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,match_id,total_runs
0,1,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,1,222.0
1,2,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,2,240.0
2,3,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,3,129.0
3,4,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,4,165.0
4,5,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,5,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,168,2009/10,Kolkata,2010-04-17,League,JD Unadkat,Eden Gardens,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,...,wickets,8.0,133.0,20.0,N,NaN,BG Jerling,RB Tiffin,168,132.0
168,169,2009/10,Dharamsala,2010-04-18,League,MS Dhoni,Himachal Pradesh Cricket Association Stadium,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,wickets,6.0,193.0,20.0,N,NaN,BF Bowden,AM Saheba,169,192.0
169,170,2009/10,Delhi,2010-04-18,League,A Symonds,Feroz Shah Kotla,Delhi Daredevils,Deccan Chargers,Deccan Chargers,...,runs,11.0,146.0,20.0,N,NaN,BR Doctrove,SK Tarapore,170,145.0
170,171,2009/10,Kolkata,2010-04-19,League,M Kartik,Eden Gardens,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,...,wickets,9.0,134.0,20.0,N,NaN,BG Jerling,RE Koertzen,171,133.0
171,172,2009/10,Mumbai,2010-04-21,Semi Final,KA Pollard,Dr DY Patil Sports Academy,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,...,runs,35.0,185.0,20.0,N,NaN,BR Doctrove,RB Tiffin,172,123.0

In [21]:
match_df.shape

(172, 22)

In [22]:
match_df['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings'],
      dtype=object)

In [23]:
teams = [
    'Royal Challengers Bengaluru',
    'Mumbai Indians',
    'Kolkata Knight Riders',
    'Rajasthan Royals',
    'Chennai Super Kings',
    'Sunrisers Hyderabad',
    'Delhi Capitals',
    'Punjab Kings',
    'Lucknow Super Giants',
    'Gujarat Titans'
]

In [34]:
# Standardize team names in matches DataFrame (BEFORE filtering)
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils', 'Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils', 'Delhi Capitals')
match_df['toss_winner'] = match_df['toss_winner'].str.replace('Delhi Daredevils', 'Delhi Capitals')
match_df['winner'] = match_df['winner'].str.replace('Delhi Daredevils', 'Delhi Capitals')
match_df['team1'] = match_df['team1'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
match_df['team2'] = match_df['team2'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
match_df['toss_winner'] = match_df['toss_winner'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
match_df['winner'] = match_df['winner'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')  # Fix winner
match_df['team1'] = match_df['team1'].str.replace('Kings XI Punjab', 'Punjab Kings')
match_df['team2'] = match_df['team2'].str.replace('Kings XI Punjab', 'Punjab Kings')
match_df['toss_winner'] = match_df['toss_winner'].str.replace('Kings XI Punjab', 'Punjab Kings')
match_df['winner'] = match_df['winner'].str.replace('Kings XI Punjab', 'Punjab Kings')  # Fix winner
match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['toss_winner'] = match_df['toss_winner'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['winner'] = match_df['winner'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')  # Fix winner

In [35]:
match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

In [36]:
match_df['team1'].unique()

array(['Royal Challengers Bengaluru', 'Punjab Kings', 'Delhi Capitals',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Sunrisers Hyderabad', 'Chennai Super Kings'], dtype=object)

In [37]:
match_df['team2'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Royal Challengers Bengaluru', 'Sunrisers Hyderabad',
       'Punjab Kings', 'Delhi Capitals', 'Mumbai Indians'], dtype=object)

In [38]:
match_df.shape

(172, 22)

In [39]:
# Duckworth-Lewis-Stern (DLS) method
match_df['method'].value_counts()

method
D/L    5
Name: count, dtype: int64

In [40]:
# DLS-affected matches

match_df[match_df['method'] == 'D/L'][['team1', 'team2', 'toss_winner', 'method']]

                    team1                  team2            toss_winner method
38         Delhi Capitals           Punjab Kings         Delhi Capitals    D/L
41  Kolkata Knight Riders    Chennai Super Kings  Kolkata Knight Riders    D/L
60         Delhi Capitals           Punjab Kings         Delhi Capitals    D/L
63           Punjab Kings  Kolkata Knight Riders  Kolkata Knight Riders    D/L
89    Chennai Super Kings           Punjab Kings    Chennai Super Kings    D/L

In [41]:
# Lets consider matches where (DLS) method was not applied

match_df = match_df[match_df['method'] != 'D/L']

In [42]:
match_df.columns.tolist()

['id',
 'season',
 'city',
 'date',
 'match_type',
 'player_of_match',
 'venue',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'winner',
 'result',
 'result_margin',
 'target_runs',
 'target_overs',
 'super_over',
 'method',
 'umpire1',
 'umpire2',
 'match_id',
 'total_runs']

In [43]:
# extracting features from match dataset
match_df = match_df[['match_id','city','winner','total_runs','date']]
match_df.head()

   match_id        city                       winner  total_runs        date
0         1   Bangalore        Kolkata Knight Riders       222.0  2008-04-18
1         2  Chandigarh          Chennai Super Kings       240.0  2008-04-19
2         3       Delhi               Delhi Capitals       129.0  2008-04-19
3         4      Mumbai  Royal Challengers Bengaluru       165.0  2008-04-20
4         5     Kolkata        Kolkata Knight Riders       110.0  2008-04-20

In [44]:
# Replace old team names with new ones in delivery_df
delivery['batting_team'] = delivery['batting_team'].str.replace('Delhi Daredevils', 'Delhi Capitals')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Delhi Daredevils', 'Delhi Capitals')

delivery['batting_team'] = delivery['batting_team'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')

delivery['batting_team'] = delivery['batting_team'].str.replace('Kings XI Punjab', 'Punjab Kings')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Kings XI Punjab', 'Punjab Kings')

delivery['batting_team'] = delivery['batting_team'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

In [45]:
delivery = delivery[delivery['batting_team'].isin(teams)]
delivery = delivery[delivery['bowling_team'].isin(teams)]

In [46]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,1,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,1,SC Ganguly,P Kumar,BB McCullum,0.0,1.0,1.0,legbyes,0.0,NaN,NaN,NaN
1,1,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,2,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
2,1,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,3,BB McCullum,P Kumar,SC Ganguly,0.0,1.0,1.0,wides,0.0,NaN,NaN,NaN
3,1,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,4,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
4,1,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,5,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN

In [47]:
delivery_df = match_df.merge(delivery, on = 'match_id')

In [48]:
delivery_df = delivery_df[delivery_df['inning'] == 2]

In [49]:
delivery_df.head()

,match_id,city,winner,total_runs_x,date,inning,batting_team,bowling_team,over,ball,...,bowler,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
124,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1,...,AB Dinda,W Jaffer,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN
125,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,2,...,AB Dinda,R Dravid,0.0,1.0,1.0,wides,0.0,NaN,NaN,NaN
126,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,3,...,AB Dinda,R Dravid,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
127,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,4,...,AB Dinda,R Dravid,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN
128,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,5,...,AB Dinda,W Jaffer,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN

In [50]:
delivery_df.shape

(19237, 21)

In [52]:
delivery_df.loc[:, 'current_score'] = delivery_df.groupby('match_id')['total_runs_y'].cumsum()

In [53]:
delivery_df.head()

,match_id,city,winner,total_runs_x,date,inning,batting_team,bowling_team,over,ball,...,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score
124,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1,...,W Jaffer,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,1.0
125,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,2,...,R Dravid,0.0,1.0,1.0,wides,0.0,NaN,NaN,NaN,2.0
126,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,3,...,R Dravid,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,2.0
127,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,4,...,R Dravid,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,3.0
128,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,5,...,W Jaffer,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,4.0

In [54]:
delivery_df.head()

,match_id,city,winner,total_runs_x,date,inning,batting_team,bowling_team,over,ball,...,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score
124,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1,...,W Jaffer,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,1.0
125,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,2,...,R Dravid,0.0,1.0,1.0,wides,0.0,NaN,NaN,NaN,2.0
126,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,3,...,R Dravid,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,2.0
127,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,4,...,R Dravid,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,3.0
128,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,5,...,W Jaffer,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,4.0

In [55]:
# Now lets see how many balls left

delivery_df['balls_left'] = 120 - (delivery_df['over']*6 + delivery_df['ball'])

In [56]:
delivery_df

,match_id,city,winner,total_runs_x,date,inning,batting_team,bowling_team,over,ball,...,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,balls_left
124,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1,...,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,1.0,119
125,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,2,...,0.0,1.0,1.0,wides,0.0,NaN,NaN,NaN,2.0,118
126,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,3,...,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,2.0,117
127,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,4,...,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,3.0,116
128,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,5,...,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,4.0,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39832,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,16,6,...,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,127.0,18
39833,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,16,7,...,2.0,0.0,2.0,NaN,0.0,NaN,NaN,NaN,129.0,17
39834,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,17,1,...,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,130.0,17
39835,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,17,2,...,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,131.0,16
39836,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,17,3,...,4.0,0.0,4.0,NaN,0.0,NaN,NaN,NaN,135.0,15

In [57]:
# now lets see how many wickets are left
# If a player is out, it is recorded next to their name; otherwise, it is marked as NaN.
# We will fill nan with 0

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")

# Wherever there is a name, we will replace it with 1.

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x: x if x == '0' else "1")

#Here,`x if x == 0` ensures that if the value is 0,it remains unchanged,and it replaces other values (names) with 1

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype('int')

# lets count how many wickets have been taken

wickets= delivery_df.groupby("match_id")['player_dismissed'].cumsum().values

# Lets see how many wickets are left

delivery_df['wickets_left'] = 10- wickets

In [58]:
delivery_df.head()

,match_id,city,winner,total_runs_x,date,inning,batting_team,bowling_team,over,ball,...,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,balls_left,wickets_left
124,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1,...,0.0,1.0,NaN,0.0,0,NaN,NaN,1.0,119,10
125,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,2,...,1.0,1.0,wides,0.0,0,NaN,NaN,2.0,118,10
126,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,3,...,0.0,0.0,NaN,0.0,0,NaN,NaN,2.0,117,10
127,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,4,...,0.0,1.0,NaN,0.0,0,NaN,NaN,3.0,116,10
128,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,5,...,0.0,1.0,NaN,0.0,0,NaN,NaN,4.0,115,10

In [59]:
delivery_df.tail()

,match_id,city,winner,total_runs_x,date,inning,batting_team,bowling_team,over,ball,...,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,balls_left,wickets_left
39832,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,16,6,...,0.0,1.0,NaN,0.0,0,NaN,NaN,127.0,18,9
39833,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,16,7,...,0.0,2.0,NaN,0.0,0,NaN,NaN,129.0,17,9
39834,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,17,1,...,0.0,1.0,NaN,0.0,0,NaN,NaN,130.0,17,9
39835,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,17,2,...,0.0,1.0,NaN,0.0,0,NaN,NaN,131.0,16,9
39836,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,17,3,...,0.0,4.0,NaN,0.0,0,NaN,NaN,135.0,15,9

In [66]:
# Current run rate (crr)= runs/overs
delivery_df.loc[:, 'crr'] = (delivery_df['current_score']*6)/(120 - delivery_df['balls_left'])

In [68]:
# If winner and batting team are same then result will be 1 esle 0
def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0

In [69]:
delivery_df['result'] = delivery_df.apply(result, axis = 1)

In [70]:
delivery_df

,match_id,city,winner,total_runs_x,date,inning,batting_team,bowling_team,over,ball,...,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,balls_left,wickets_left,crr,result
124,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1,...,NaN,0.0,0,NaN,NaN,1.0,119,10,6.000000,0
125,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,2,...,wides,0.0,0,NaN,NaN,2.0,118,10,6.000000,0
126,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,3,...,NaN,0.0,0,NaN,NaN,2.0,117,10,4.000000,0
127,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,4,...,NaN,0.0,0,NaN,NaN,3.0,116,10,4.500000,0
128,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,5,...,NaN,0.0,0,NaN,NaN,4.0,115,10,4.800000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39832,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,16,6,...,NaN,0.0,0,NaN,NaN,127.0,18,9,7.470588,1
39833,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,16,7,...,NaN,0.0,0,NaN,NaN,129.0,17,9,7.514563,1
39834,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,17,1,...,NaN,0.0,0,NaN,NaN,130.0,17,9,7.572816,1
39835,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,17,2,...,NaN,0.0,0,NaN,NaN,131.0,16,9,7.557692,1
39836,171,Kolkata,Kolkata Knight Riders,133.0,2010-04-19,2,Kolkata Knight Riders,Mumbai Indians,17,3,...,NaN,0.0,0,NaN,NaN,135.0,15,9,7.714286,1

In [71]:
delivery_df['result'].value_counts()

result
1    9950
0    9287
Name: count, dtype: int64

In [77]:
delivery_df.to_csv("delivery_df.csv", index=False)

In [80]:
teams

['Royal Challengers Bengaluru',
 'Mumbai Indians',
 'Kolkata Knight Riders',
 'Rajasthan Royals',
 'Chennai Super Kings',
 'Sunrisers Hyderabad',
 'Delhi Capitals',
 'Punjab Kings',
 'Lucknow Super Giants',
 'Gujarat Titans']

In [81]:
delivery_df['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala'],
      dtype=object)

In [84]:
df = pd.read_csv('delivery_df.csv')

In [85]:
df.head()

,match_id,city,winner,total_runs_x,date,inning,batting_team,bowling_team,over,ball,...,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,balls_left,wickets_left,crr,result
0,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1,...,NaN,0.0,0,NaN,NaN,1.0,119,10,6.0,0
1,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,2,...,wides,0.0,0,NaN,NaN,2.0,118,10,6.0,0
2,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,3,...,NaN,0.0,0,NaN,NaN,2.0,117,10,4.0,0
3,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,4,...,NaN,0.0,0,NaN,NaN,3.0,116,10,4.5,0
4,1,Bangalore,Kolkata Knight Riders,222.0,2008-04-18,2,Royal Challengers Bengaluru,Kolkata Knight Riders,0,5,...,NaN,0.0,0,NaN,NaN,4.0,115,10,4.8,0